### ISSUE TITLE
team balancing: max number difference not working

### ISSUE THREAD

**Issue by TerranUlm** [TerranUlm/MyBB-Plugin-OPT-Armies#5]
The setting for the max teamsize difference is not working.

**Comment by opt-natter** [comment]
Line 1853 change 
if ($army[ 'is locked' ] == 1)
 to
if ($army[ 'is_locked' ] == 1)

Line 3080 add
$army['members'] =$army_members;

**Comment by TerranUlm** [comment]
nice finds, but I just noticed another flaw in the code around line 3080 so I have to test it first before I put it in the master branch.

**Comment by TerranUlm** [comment]
Der Fix funktioniert wohl, Thema zu :dancer:
